# Data Manipulation

We will start by introducing PyTorch's tensors- a primary tool for storing and manipulating data. They are similar to NumPy's arrays but they have a few advantages: accelerated computations on GPU and support for automatic differentiation.

##  Getting Started

In [1]:
import torch

In [9]:
# create a tensor
x = torch.arange(12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [10]:
# check shape
x.shape

torch.Size([12])

In [11]:
# reshape
x = x.reshape((3, 4))

In [12]:
# check shape
x.shape

torch.Size([3, 4])

In [8]:
# reshaping by placing -1
x = torch.arange(12)
x = x.reshape(-1, 4)
x.shape

torch.Size([3, 4])

In [24]:
# view is another method for reshaping
x = torch.arange(12)
x = x.view(-1, 4)
x.shape

torch.Size([3, 4])

In [14]:
# empty method
torch.empty((3, 4))

tensor([[ 0.0000e+00, -2.0000e+00,  0.0000e+00, -2.0000e+00],
        [ 1.1210e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.4013e-45,  1.8754e+28,  4.0611e-08]])

In [18]:
# tensor of zeros
torch.zeros(2, 3, 4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
# tensor of ones
torch.ones(2, 3, 4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [22]:
# create a tensor from a list
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
# construct a randomly initialized matrix
torch.rand(5, 3)

tensor([[0.4822, 0.7316, 0.1038],
        [0.0729, 0.3323, 0.0510],
        [0.7622, 0.5664, 0.1936],
        [0.5609, 0.7880, 0.6916],
        [0.3150, 0.7094, 0.0900]])

## Operations

In [27]:
# element-wise functions
x = torch.tensor([1, 2, 3, 4])
y = torch.ones_like(x) * 2
print('x = ', x)
print('x + y =', x + y)
print('x - y =', x - y)
print('x / y =', x / y)

x =  tensor([1, 2, 3, 4])
x + y = tensor([3, 4, 5, 6])
x - y = tensor([-1,  0,  1,  2])
x / y = tensor([0, 1, 1, 2])


In [35]:
# more operations can be applied element-wise, such as exponentiation
x = torch.tensor([1, 2, 3, 4], dtype=torch.float)
x.exp()

tensor([ 2.7183,  7.3891, 20.0855, 54.5982])

In [41]:
# matrix multiplication
x = torch.arange(12).reshape(3, 4)
y = torch.tensor([[2, 1, 4, 3], 
                  [1, 2, 3, 4], 
                  [4, 3, 2, 1]])
torch.matmul(x, torch.transpose(y, 0, 1))

tensor([[ 18,  20,  10],
        [ 58,  60,  50],
        [ 98, 100,  90]])

In [44]:
# concatenate
torch.cat([x, y], 0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]])

In [45]:
torch.cat([x, y], 1)

tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]])

In [46]:
# logical statements
x == y

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [47]:
# sum all elements
x.sum()

tensor(66)

## Saving Memory

Every time we ran an operation, we allocate new memory to host its results. We demonstrate this by Python's ``id`` function. This might be undesirable in ML.

In [49]:
before = id(y)
y = y + x
after = id(y)
print(before == after)

False


In [50]:
before = id(y)
y[:] = x + y
after = id(y)
print(before == after)

True


In [51]:
before = id(y)
y += x
after = id(y)
print(before == after)

True


In [53]:
before = id(y)
torch.add(x, y, out=y)
after = id(y)
print(before == after)

True


Pytorch can perform in-place operations already.

## NumPy Bridge

In [54]:
import numpy as np

In [55]:
a = x.numpy()
print(type(a))
b = torch.from_numpy(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


# Linear Algebra

In [56]:
# create a 5 by 4 matrix
A = torch.arange(20).view(5, 4)

In [63]:
# transpose
A.transpose(0, 1)

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [72]:
# norms
x = torch.arange(4, dtype=torch.float)
x.norm(p=2)

tensor(3.7417)

In [71]:
x.norm(p=2)

tensor(3.7417)

# Automatic Differentiation

As a toy example, say that we are interested in differentiating the mapping $y = 2 \mathbf{x}^T \mathbf{x}$ with respect to a column vector $\mathbf{x}$.

In [74]:
x = torch.arange(4, dtype=torch.float,
                 requires_grad=True)

In [75]:
y = 2 * torch.dot(x, x)

In [76]:
y.grad_fn

We can now automatically find the gradient of all inputs by calling the ``backward`` function.

In [77]:
y.backward()

The gradient of the function $y = 2 \mathbf{x}^T \mathbf{x}$ with respect to $\mathbf{x}$ should be $4 \mathbf{x}$. Now, let's verify that the gradient produced is correct.

In [79]:
x.grad - 4 * x

tensor([0., 0., 0., 0.], grad_fn=<SubBackward0>)

You can also stop autograd from tracking history on Tensors with ``.requires_grad=True`` by wrapping the code block in with ``torch.no_grad()``:

In [81]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [82]:
y.requires_grad

True